<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf82367fa311a58bfbcf221fb8beb9853
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Pupilcp\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Pupilcp\\' =>
        array (
            0 => __DIR__ . '/..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf82367fa311a58bfbcf221fb8beb9853::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf82367fa311a58bfbcf221fb8beb9853::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
